project:
  type: website

execute: 
  freeze: auto

website:
  title: "RchaeoStats"
  page-navigation: true

  sidebar: 
    style: docked
    logo: images/hexsticker.png
    contents:
      - href: index.qmd
        text: Course Overview
      - href: assignments.qmd
      - section: Materials 
        contents: 
        - section: Core
        - href: docs/00_install-r-rstudio.qmd
          text: 00 - Getting Started
        - href: docs/01_r-basics.qmd
          text: 01 - R Basics
        - href: docs/02_workflow.qmd
          text: 02 - An Example Workflow
        - href: docs/03_rstudio-project.qmd
          text: 03 - Getting Organised
        - href: docs/04_cleaning-data.qmd
          text: 04 - Cleaning Data
        - section: EDA
        - href: docs/05_visualising-data.qmd
          text: 05 - Visualising Data
        - href: docs/06_transforming-data.qmd
          text: 06 - Transforming Data
        - section: Extensions
        - href: docs/08_communicating-results.qmd
          text: 08 - Communicating Results
      - section: Slides
        contents: 
        - href: slides/content/00_welcome.qmd
          text: 00 - Welcome
        - href: slides/content/01_rstudio-project.qmd
          text: 01 - RStudio Projects

format:
  html:
    theme: theme.scss
    css: styles.css
